/*
This file contains creation of users_custom_checkups table that stores user custom input for 
medical checkups related with work medicine, individual treatments etc. 
Input can optionally include last checkup date, frequency and next appointment date.
*/


create table users_custom_checkups (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
									, user_id integer not null references users(id)
									, checkup_name varchar(100) not null
									, last_checkup_date date null
									, cycle_days integer null
									, next_checkup_date date null
									, last_filled timestamp not null default localtimestamp);

-- User should provide either frequency or next checkup date otherwise in response the final view 
-- will show current date for next appointment			
insert into users_custom_checkups (user_id, checkup_name, last_checkup_date, cycle_days, next_checkup_date) values
	(1, 'Sprawdzenie kolana', '2022-04-23', null, '2022-06-30')
	, (1, 'Medycyna pracy', '2022-02-02', 600, null)
	, (2, 'MRA', null, null, '2022-07-01')
	, (3, 'MRA', null, null, null);