/*
This file contains creation of users_checkup_history table that stores user second part of form output 
regarding last date of assigned before medical checkup (users_checkups view) and its result (whether is was good or bad). 
Record insertion is meant to be handled in code.
*/


create table users_checkup_history (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
									, user_id integer not null references users(id)
									, checkup_id integer not null references medical_checkups(id)
									-- , medical_checkup varchar(100) not null
									, last_checkup_date date null
									, is_last_checkup_good smallint null
									, last_filled timestamp not null default localtimestamp);

/*
For each of assigned in users_checkups checkup user should be asked separately for the last date.
Each answer for each checkup will be stored as a new row, just like in the example below:
*/

-- UPDATE: no need to insert records with null values				
insert into users_checkup_history (user_id, checkup_id, last_checkup_date, is_last_checkup_good) values
	(1, 1, '2022-01-23', 1)
	, (1, 2, '2022-01-30', 1)
	, (1, 3, '2022-03-27', 1)
	, (1, 5, '2022-04-09', 0)
	, (1, 9, '2022-03-05', 0)
	, (1, 11, '2022-03-21', 0)
	, (1, 12, '2022-03-24', 1)
	, (1, 16, '2022-03-14', 0)
	, (1, 18, '2022-02-06', 1)
	, (1, 36, '2022-02-27', 0)
	, (1, 45, '2022-02-25', 1);


-- Testing users_calendar view whether it will show only the newest checkup 
insert into users_checkup_history (user_id, checkup_id, last_checkup_date, is_last_checkup_good) values
	(1, 1, '2055-07-13', 1);